= CSoftZ Spring Boot POC (chuck-norris-wrapper-service) README

V2020.1.0

This project only holds Spring Web Flux related only stuff. It is a REST API end-point to wrap calls for the
https://api.chucknorris.io[chucknorris.io is a free JSON API for hand curated Chuck Norris facts].

This REST end-point is built only for POC and educational purposes.

The following is the list of components used.

* *JaCoCo Plugin* V0.8.6
* *Lombok* V1.18.16 (curated from Spring Boot Starters).
* *Spring Boot* V2.4.1 with the following modules: Spring WebFlux, Actuator, DevTools, Configuration Processor
* *Spring RestDocs* V2.0.5, requires _Spring Framework_ 5.0.2 or later.

For testing purposes

* *Spring Test*
* *Reactor Test*
* *AssertJ*
* *Mockito*
* *Spring Rest MockMvc*
* *Spring Rest WebClient Test*

Since version 2020.1.0 the project uses JUnit 5 exclusively.

Migrating from JUnit 4 to JUnit 5
https://www.baeldung.com/junit-5-migration

Five Tools to Improve Your Java Code
https://developer.okta.com/blog/2019/12/20/five-tools-improve-java

Sometimes it is needed to skip both *PMD* and *SpotBugs*, use the following command.

[NOTE]
====
You can skip PMD using the command line arg
#-Dpmd.skip#, similarly with SpotBugs, #-Dspotbugs.skip#. For example: mvn verify -Dpmd.skip -Dspotbugs.skip would skip both.

====

